### ISSUE TITLE
[BUG] PCA KeyError: 'df_pca'

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#169]
```
Exception on /pca/download [GET]
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
   return func(*args, **kwargs)
 File "/flaski/flaski/apps/routes/pca.py", line 197, in pca
   df_pca=pd.read_json(session["df_pca"])
 File "/usr/local/lib/python3.7/dist-packages/werkzeug/local.py", line 378, in <lambda>
   __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: 'df_pca'
```

**Comment by jorgeboucas** [comment]
this seems to be an issue of using the browsers go back function when `Enable multiple Apps per session.` is not enabled.
