### ISSUE TITLE
[BUG] david import

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#224]
```
Exception on /david/_dash-update-component [POST]
Traceback (most recent call last):
 File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
   response = self.full_dispatch_request()
 File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
   rv = self.dispatch_request()
 File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
 File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
   return current_app.ensure_sync(func)(*args, **kwargs)
 File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1274, in dispatch
   ctx.run(
 File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 440, in add_context
   output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
 File "/myapp/myapp/routes/apps/david.py", line 823, in read_session_redis
   return imp["session_import"], imp["sessionfilename"], imp["last_modified"]
KeyError: 'session_import'
```

**Comment by jorgeboucas** [comment]
- not able to reproduce
- possible issue with time to delete from redid
- currently David sessions can be exported but only uploaded and loaded through the Storage route
