### ISSUE TITLE
Dendogram

### ISSUE THREAD

**Issue by jorgeboucas** [mpg-age-bioinformatics/flaski#55]

**Comment by jorgeboucas** [comment]
I've tried to upload a gene expression table. One gene per row, one sample per column:
```
Traceback (most recent call last):
  File "/flaski/flaski/apps/routes/idendrogram.py", line 84, in idendrogram
 fig=make_figure(df,plot_arguments)
  File "/flaski/flaski/apps/main/idendrogram.py", line 102, in make_figure
 distfun=lambda x: pdist(x, pa["dist_func"]),linkagefun=lambda x: sch.linkage(x, pa["link_func"]))
  File "/usr/local/lib/python3.7/dist-packages/plotly/figure_factory/_dendrogram.py", line 99, in create_dendrogram
 color_threshold=color_threshold,
  File "/usr/local/lib/python3.7/dist-packages/plotly/figure_factory/_dendrogram.py", line 146, in __init__
 X, colorscale, distfun, linkagefun, hovertext, color_threshold
  File "/usr/local/lib/python3.7/dist-packages/plotly/figure_factory/_dendrogram.py", line 298, in get_dendrogram_traces
 d = distfun(X)
  File "/flaski/flaski/apps/main/idendrogram.py", line 102, in 
 distfun=lambda x: pdist(x, pa["dist_func"]),linkagefun=lambda x: sch.linkage(x, pa["link_func"]))
  File "/usr/local/lib/python3.7/dist-packages/scipy/spatial/distance.py", line 2061, in pdist
 metric_name, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/scipy/spatial/distance.py", line 302, in _validate_pdist_input
 X = _convert_to_type(X, out_type=typ)
  File "/usr/local/lib/python3.7/dist-packages/scipy/spatial/distance.py", line 187, in _convert_to_type
 return np.ascontiguousarray(X, dtype=out_type)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py", line 179, in ascontiguousarray
 return array(a, dtype, copy=False, order='C', ndmin=1)
ValueError: could not convert string to float: 'WBGene00197333'

Something went wrong. Review your input and press Submit.
```

**Comment by jorgeboucas** [comment]
-  [ ] it should be possible to decide which columns are used for the dendrogram and which one is used as row labels

**Comment by jorgeboucas** [comment]
this app turned out to be to redundant with clustered heat maps and useless as a stand alone. Quality of figure was also subpar specially in the way the distance lines were plotted.
